### ISSUE TITLE
Confirming the medium of reporting security vulnerabilities

### ISSUE THREAD

**Issue by almndbtr** [ourzora/v3#131]
## Summary

If we want to participate in the _security vulnerability_ portion of the community audit, what communication method does the @ourzora team prefer? 💭

### Reconciling differences

In the [Enter Zora V3](https://zine.zora.co/zora-v3), I see that the `Community Bug Bounty` section says to email either of these addresses:

> We have an up to 25 ETH community bug bounty for any vulnerabilities discovered. If you find any vulnerability that could result in the loss of user funds or NFTs, reach out to t@zora.co or support@zora.co

However, the [Community Audit](https://github.com/ourzora/v3#community-audit) section of this README isn't particularly clear on whether or not we should be emailing those addresses, commenting directly in the PR, or taking another method. 😅

---

🐦  Twitter Equivalent of this issue: [tweet](https://twitter.com/almndbtr/status/1487171403518410754?s=20&t=JNewo7wgJzl36CoDzU3rPQ)

**Comment by almndbtr** [comment]
Looking at some Prior Art, GitHub has a [coordinated disclosure](https://docs.github.com/en/code-security/security-advisories/about-coordinated-disclosure-of-security-vulnerabilities) article that may be of interest, in addition to a [best practices for vulnerability reporters](https://docs.github.com/en/code-security/security-advisories/about-coordinated-disclosure-of-security-vulnerabilities#best-practices-for-vulnerability-reporters) guide. 

Getting clarity on the "how" would be great, especially if the team prefers to receive these reports privately rather than publicly (via issue, pull request, Twitter, Discord, etc.).

**Comment by tbtstl** [comment]
Hey @almndbtr, if the security vulnerability is in an undeployed module, feel free to leave a comment directly in the PR. If it's already been deployed, you can email me directly – t@zora.co.

Thanks!

**Comment by tbtstl** [comment]
I'll make a note to add this to the Contributing section of the README as well

**Comment by almndbtr** [comment]
@tbtstl - Thanks for the prompt reply! That helps. 👍

I want to make sure I'm on the same page, in the hopes that it's not just clear for me but others who might come across this:

- Is every [open PR in this repo](https://github.com/ourzora/v3/pulls) technically an `undeployed` module? Or, is there some other signifier that makes them undeployed?
- Would the ten Etherscan Addresses (Rinkeby; Mainnet) listed in [Enter Zora V3](https://zine.zora.co/zora-v3) be considered "deployed" modules? Is it safe to consider [docs.zora.co's Zora V3 Core Addresses](https://docs.zora.co/docs/smart-contracts/zora-V3#zora-v3-core-addresses) as the "authoritative" source for all `deployed` modules?

**Comment by tbtstl** [comment]
@almndbtr, every open PR is indeed undeployed – however only the modules marked `Community Audit` or `Zora Bug Bounty` are "complete" and ready for audit reports. Specifically, `Zora Bug Bounty` PRs are available for the bug bounty program of up to 25 ETH, as outlined in the README.

PRs marked `Draft / RFC` aren't code complete yet, but anyone is welcome to ask questions / suggest improvements on those PRs as well.

docs.zora.co would be the best place to check for deployed modules.

**Comment by almndbtr** [comment]
I appreciate the succinct response. That's crystal clear to me. 💎

I will leave this open until the README is updated [with your input](https://github.com/ourzora/v3/issues/131#issuecomment-1024656969). Thanks again for your time, @tbtstl! 🌜🌞🌛

**Comment by kulkarohan** [comment]
just updated!

**Comment by almndbtr** [comment]
I see the [changes reflected in README](https://github.com/ourzora/v3#community-audit) as of https://github.com/ourzora/v3/commit/63e4f750a2c1038ea36f665a42f2dcc02d0c70e1. I will close this, thanks again @kulkarohan  & @tbtstl ! 😎
