### ISSUE TITLE
Is there a calendar or public roadmap of upcoming Community Audits?

### ISSUE THREAD

**Issue by almndbtr** [ourzora/v3#136]
Hi @ourzora! 

Is there a calendar or public roadmap of upcoming Community Audits? 💭

After reviewing https://github.com/ourzora/v3/pull/126, I'm curious about when the next Community Audit is so I can come prepared. 

In the meantime, I'll read through the existing [`Draft / RFC`](https://github.com/ourzora/v3/labels/Draft%20%2F%20RFC)s and take notes.

Thank you! 🌞

**Comment by kulkarohan** [comment]
hey @almndbtr we're planning on opening up Reserve Auction and Collection Offers today! i'd start with Reserve Auction, the current Collection Offers draft is a bit outdated

**Comment by almndbtr** [comment]
Roger that. 🖤

I appreciate the heads-up. I will close this out then, but if a public calendar or similar comes up, totally here for it!

Much thanks @kulkarohan ✨

**Comment by kulkarohan** [comment]
got you. and thank YOU 👑

**Comment by tbtstl** [comment]
Hey @almndbtr, we're still dialing in the exact cadence / scheduling for Community Reviews, but will keep the idea of a calendar in mind – I think that makes a ton of sense
