### ISSUE TITLE
Application Error on the Market and Profile Page on the UI

### ISSUE THREAD

**Issue by gigabvgatti** [ourzora/v3#191]
There is a persistent user interface problem that has been hindering me from accessing any NFTs which were created via pre-Create "mint" function for 1/1 editions such as .txt and .md files, and my personal profile page, for almost a month now.

It affects market dot zora dot co links with exceptions at time. Several other friends have reported encountering the same problem across both Chromium-based, and other types of browsers both on desktop and mobile.

I hope this is the right place open this issue.
<img width="980" alt="Screenshot 2022-12-14 at 01 54 51" src="https://user-images.githubusercontent.com/11991363/209411437-529154f4-4da9-451b-a0cb-b6795790c7a9.png">

**Comment by iainnash** [comment]
We appreciate your report but the best venue for this would be our support channels.

In any case can you provide a link to the page with this issue?
